# Generated by Django 5.1.4 on 2024-12-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_form', '0002_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
