# Generated by Django 5.1.4 on 2024-12-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('stock', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('additional_data', models.JSONField(default=dict)),
            ],
        ),
    ]
